/* eslint-disable indent */
export const all_routes = {
  dashboard: "/admin-dashboard",
  institution:'/institution',
  addinstitution:'/addinstitution',
  reports : "/reports",
  latestnews:"/latest-news",
  createlatestnews:"/create-news",
  editnews:"/edit-news",
  studentslist:"/students",
  mentorslist:"/mentors",
  teamslist:"/teams",
  diesshift:"/admin-mentor-shift",
  searchshift:"/search-mentor-shift",

  coodiesshift:"/state-mentor-shift",

  adminlist:"/admins",
  statelist:"/states",
  adminpermission:"/admin-permission",
  eadminbukAC:"/eadmin/eadmin-BulkAC",
  eadmindropdown:"/eadmin-update",
  mentortableview:"/mentor-view",
  popup:"/popup",
  createemail:"/create-email",
  resendemail:"/resend-email",
editeval:"/edit-evaluator",
  mentordetails:"/mentor-details",
  studentreport:"Student-Report",
  mentorEdit:"/admin-mentor-edit",
  instruction:"/instruction",
  studenttableview:"/student-view",
  stuedit:"student-edit",
  diescode:"/diescode-search",
  coodies:"/coo-search",
  diesview:"/diescode-view",
  cooview:"/coo-view",
  searchCid:"/search-cid",
coosupport:"/state-support",
adminsupport:"/admin-support",
adminresponse:"/admin/support-journey/ans-ticket",
statewise:"state-wise",
editstatewise:"edit-state-wise",
ideareport:"/idea-report",
cooresponse:"/coordinator/support-journey/ans-ticket",
institutionreport:"/institution-report",
  diesedit:"/diescode-mentor-edit",
  createpopup:"/create-popup",
  EmailList:"/emailList",
  reportsregistration : "/reportsregistration",
  reportsteacher : "/reportsteacher",
  adminresources : "/adminresources",
  stateresources : "/stateresources",
  profile:"/profile",
mentorprofile:"/mentorprofile",
  mentoreditprofile:"/mentoreditprofile",
  createResource : "/createResource",
  createStateResource : "/createStateResource",

  editResource : "/editResource",
  editStateResource : "/editStateResource",

  editinstitution:"/edit-institution",
  mentordashboard: "/teacher-dashboard",
  teamdashboard: "/team-dashboard",
  teamProfile: "/team-profile",
  studentProfile: "/student-profile",
  studentdashboard: "/student-dashboard",
  studentCertificate: "/certificate",
  studentpostsurvey: "/studentpostsurvey",
  studentpresurvey: "/studentpresurvey",
  createteam: "/createteam",
  addstudent: "/addstudent",
  studentedit: "/studentedit",
  tecresource: "/tecresource",
  studentresource: "/studentresource",
  mentorpresurvey: "/mentorpresurvey",
  mentorpostsurvey: "/mentorpostsurvey",
  mentorcourse: "/mentorcourse/:id",
  studentcourse: "/studentcourse/:id",
  instructions : "/instructions",
  instructionstu : "/instructionstu",
  mentorsupport: "/mentorsupport",
  mentorcertificate: "/mentorcertificate",
  mentorchangepwd: "/mentorchangepwd",
  mentorteams: "/mentorteams",
  idea: "/idea",
  badge:"/badges",
  stateregist:"/state-registration",
  schoolcoo:"/school-report",
  studentcoo:"/studentcoo-report",
  intitutioncoo:"/institution-report",
  intitutioncoostate:"/state-institution-report",
eadminstats:"/eadmin/evaluationStatus/viewlist",
  badgeTeacher:"/teacherBadges",
  statedashboard: "/state-dashboard",
  /// Eadmin///////
  eadmindashboard: "/eadmin/dashboard",
  eadminevaluation:"/eadmin/evaluationStatus",
eadminEvaluationProcess:"/eadmin/evaluationProcess",
eadminevaluator:"/eadmin/evaluator",
eadminfinal:"/eadmin/evaluationStatus/viewfinallist",
eadminRest:"/eadmin-changepwd",
eadminDist:'/eadmin/selectingDistricts-evaluationProcess',
evalState:"/evaluator/selecting-states",
evalinstructions:"/evaluator/instructions",
evalsubmit:"/evaluator/submitted-ideas",
evalsubmitwo:"/evaluator2/submitted-ideas",
evalchange:"/evaluator/change-password",
evlL1:"/evaluator/evaluated-ideas",
evlL2:"/evaluator/evaluated-ideasL2",
evlProfile:"/evaluator-profile",
evalReports:"/reports-card",
evalL1:"/l1-report",
evalL2:"/l2-report",
evalL3:"/l3-report",



  adminpassword: "/admin-password",
};
